export const FORM_PROJECT = 'FORM_PROJECT'
export const ADD_PROJECT = 'ADD_PROJECT'
export const GET_PROJECTS = 'GET_PROJECTS'
export const VALIDATE_FORM = 'VALIDATE_FORM'
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const PROJECT_ERROR = 'PROJECT_ERROR'

export const GET_TASKS = 'GET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const VALIDATE_TASK_FORM = 'VALIDATE_TASK_FORM'
export const DELETE_TASK = 'DELETE_TASK'
export const ACTUAL_TASK = 'ACTUAL_TASK'
export const EDIT_TASK = 'EDIT_TASK'
export const TASK_ERROR = 'TASK_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const GET_USER = 'GET_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'